# Dependabot configuration for TypeComposer Docs project
# This configuration monitors dependencies for the docs project only
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for npm (Docs project)
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `docs` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    # Group all patch and minor updates together
    groups:
      docs-development:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      docs-production:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    directory: "/docs/.github/workflows"
    schedule:
      interval: "weekly"